name: Deploy static site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4   # ✅ updated

      - name: Setup Pages
        uses: actions/configure-pages@v4   # ✅ updated

      - name: Upload artifact
        uses: actions/upload-pages
